### PR TITLE
Add progress bar

### PR DESCRIPTION
**Pull request by lazappi**
Set `progress = TRUE` in `Artifact$cache()`

### CODE REVIEW

**Comment by rcannood** [comment]
Thanks for taking care of this!

Does the python interface expose an argument to be able to turn this off and on?

**Comment by lazappi** [comment]
I don't think so but it would be easy enough to add one if you like

**Comment by rcannood** [comment]
Alright!

* Could you add an entry to the changelog?

* Can you look into why macos is failing? (probably unrelated)

**Comment by lazappi** [comment]
>     * Can you look into why macos is failing? (probably unrelated)

I think this is a **scipy** thing, I opened an issue about it already #57

**Review by rcannood — APPROVED** [review]

**Pull request merged**
