### PR TITLE
🐛 Fix CI setup

### PR DESCRIPTION
**Pull request by rcannood**
**Related to:** laminlabs/laminhub-public#29

## Description

* Make sure IPython is installed on the CI (circumvents laminlabs/laminhub-public#29)
* Install wetlab and bionty when rendering the website to make sure warnings are not triggered.
* Switch to smaller MkRm3eUKPwfnAyZMWD9v artifact when showcasing laminlabs/cellxgene.
* Make the error message when `reticulate::import("lamindb")` fails slightly more user friendly by instructing the user to also run `reticulate::py_last_error()`.

## Checklist

**Before review**

- [x] Update and regenerate man pages
- [ ] Add/update tests
- [x] Add/update examples in vignettes
- [ ] Pass CI checks

**Before merge**

- [ ] Update architecture vignette
- [ ] Update development vignette
- [ ] Update features in `README`
- [ ] Update `CHANGELOG`

### CODE REVIEW

**Comment by falexwolf** [comment]
If this resolves things, it'd be great to merge ASAP.

**Comment by falexwolf** [comment]
Ah, but looking at it it appears like the CI would be inconsistent with what the user reads. So, this seems dangerous.

**Comment by falexwolf** [comment]
The package should work just with lamindb installed, without need of bionty or wetlab.

Something very recent must have introduced these warnings and it's a shame that we didn't catch them. If `lamindb` isn't available, I'd say, we should hard error going forward.

In retrospect, I should have kept digging about this -- I still don't understand why having lamindb not available is a valid use case. Also looping in @lazappi into the discussion.

image

**Comment by rcannood** [comment]
> Ah, but looking at it it appears like the CI would be inconsistent with what the user reads. So, this seems dangerous.

I think the pkgdown CI should install these packages to trigger the least amount of warnings. The unit test CI on the other hand should be able to work without bionty and wetlab.

**Comment by lazappi** [comment]
**{reticulate}** being able to find the correct Python installation is one of the trickier things about using it. If you have everything installed in whatever your base system Python is then it should be fine but if **lamindb** is installed in a `conda`/`virtualenv` environment then you need to make sure to point **{reticulate}** to that before loading any Python packages.

I have **lamindb** only in an environment so it won't be found unless I use `reticulate::use_virtualenv(...)` or similar first (like in some of the scripts I uploaded). There are things you can do to make this easier for users like [described here](https://cran.r-project.org/web/packages/reticulate/vignettes/python_dependencies.html) but we haven't looked into it yet.

This is one of the reasons I think we should discuss switching fully to **{reticulate}** and dropping the API access, so we can make Python availability a hard dependency.

**Comment by falexwolf** [comment]
> {reticulate} being able to find the correct Python installation is one of the trickier things about using it. If you have everything installed in whatever your base system Python is then it should be fine but if lamindb is installed in a conda/virtualenv environment then you need to make sure to point {reticulate} to that before loading any Python packages.

I also learned this playing with `laminr` on Sunday.

> This is one of the reasons I think we should discuss switching fully to {reticulate} and dropping the API access, so we can make Python availability a hard dependency.

Understood. I'm also pretty convinced that this is how it should be done independent of that reason: there is too much logic in `lamindb` to re-build it here in any finite amount of time, or move behind the REST. I believe that this is why MLFlow and probably several other packages rely on reticulate to build their R clients.

**Comment by rcannood** [comment]
Turns out the reticulate/Python setup was a red herring.

Apparently calling `reticulate::import("lamindb")` in R or even `import lamindb` in Python fails if IPython is not installed.

This PR adds a temporary workaround to make sure IPython is installed and also created laminlabs/laminhub-public#29.

**Comment by falexwolf** [comment]
Customers are looking at it right now, so I'll merge it.

**Comment by falexwolf** [comment]
> This PR adds a temporary workaround to make sure IPython is installed

Thanks for quick resolution, Robrecht!

**Pull request merged**
